### ISSUE TITLE
STEAM_LOGIN_URL needs to use https

### ISSUE THREAD

**Issue by johnmain** [Mystika/django-steamauth#4]
I have recently tried using this plugin for a project.
The GetSteamID64 validation post fails so it always goes to the Login_failed page.
After doing some logging I determined that the post wasn't getting to the correct location.  So I updated the STEAM_LOGIN_URL to use https and updated the matched64ID to also have https.

I now get sent to the login success page.

**Comment by blurfx** [comment]
Thank you for letting me know about this issue. I'll solve the issue immediately.
