### ISSUE TITLE
pip install django-steamauth not installing properly.

### ISSUE THREAD

**Issue by DextrouslyMade** [Mystika/django-steamauth#7]
Hey I just tried out this library but it does not appear to be installing properly for me.
I'm using python 3.9.0, after installing it in my enviroment (plus the entire machine just to test) all I receive in the site-packages folder relating to steamauth is this folder but it's only ther dist-info.

And when I try to use I just get that there is no module called steamauth
![image](https://user-images.githubusercontent.com/43318805/118547775-cfba5680-b759-11eb-9774-fec30b93ebc3.png)

**Comment by blurfx** [comment]
I'm sorry. It fixed in `1.1.2.3`. Please uninstall the old version and install a new version.
